### ISSUE TITLE
Failure to execute on Windows. 

### ISSUE THREAD

**Issue by redknightlois** [mgrankin/over9000#3]
Executing:
```
python train.py --run 20 --woof 0 --size 128 --bs 64 --mixup 0 --sa 0 --epoch 5 --lr 1e-2 --gpu 0 --opt over9000 --sched_type flat_and_anneal --ann_start 0.5
```
Would fail with:

```
Traceback (most recent call last):
  File "train.py", line 149, in <module>
    ann_start: Param("Mixup", float)=-1.0,
  File "C:\Anaconda3\lib\site-packages\fastai\script.py", line 40, in call_parse
    func(**args.__dict__)
  File "train.py", line 154, in main
    for i in range(run)])
  File "train.py", line 154, in <listcomp>
    for i in range(run)])
  File "train.py", line 124, in train
    fit_with_annealing(learn, epochs, lr, ann_start)
  File "train.py", line 53, in fit_with_annealing
    learn.fit(num_epoch)
  File "C:\Anaconda3\lib\site-packages\fastai\basic_train.py", line 202, in fit
    fit(epochs, self, metrics=self.metrics, callbacks=self.callbacks+callbacks)
  File "C:\Anaconda3\lib\site-packages\fastai\basic_train.py", line 99, in fit
    for xb,yb in progress_bar(learn.data.train_dl, parent=pbar):
  File "C:\Anaconda3\lib\site-packages\fastprogress\fastprogress.py", line 72, in __iter__
    for i,o in enumerate(self._gen):
  File "C:\Anaconda3\lib\site-packages\fastai\basic_data.py", line 75, in __iter__
    for b in self.dl: yield self.proc_batch(b)
  File "C:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 682, in __init__
    w.start()
  File "C:\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'compose.<locals>.compose_'

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Anaconda3\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

Any idea?

**Comment by mgrankin** [comment]
It looks like `call_parse` decorator fails for some reason. Can you try that decorator alone on Windows?

https://github.com/fastai/fastai/blob/a97311738df9127ad95c8a91f5b8168e2eecddb3/fastai/script.py#L40

**Comment by redknightlois** [comment]
Don't know how to try it alone. It looks like the issue is on the 'spawning' of the process but couldnt figure out where.

**Comment by mgrankin** [comment]
Just try to run something from fastai examples, like this one

https://github.com/fastai/fastai/blob/e6409953196cfa9ab8297c2603612bdbbc18f565/examples/train_mnist.py

**Comment by mgrankin** [comment]
Or better, just try to remove the decorator and run it with https://github.com/google/python-fire

**Comment by redknightlois** [comment]
Running the examples, all fail. 

For example:
```
python train_mnist.py
```
``` 
Traceback (most recent call last):
  File "train_mnist.py", line 5, in <module>
    @call_parse
  File "C:\Anaconda3\lib\site-packages\fastai\script.py", line 40, in call_parse
    func(**args.__dict__)
  File "train_mnist.py", line 9, in main
    data = ImageDataBunch.from_folder(path, ds_tfms=tfms, bs=64).normalize(imagenet_stats)
  File "C:\Anaconda3\lib\site-packages\fastai\vision\data.py", line 108, in from_folder
    if valid_pct is None: src = il.split_by_folder(train=train, valid=valid)
  File "C:\Anaconda3\lib\site-packages\fastai\data_block.py", line 209, in split_by_folder
    return self.split_by_idxs(self._get_by_folder(train), self._get_by_folder(valid))
  File "C:\Anaconda3\lib\site-packages\fastai\data_block.py", line 204, in _get_by_folder
    return [i for i in range_of(self) if (self.items[i].parts[self.num_parts] if isinstance(self.items[i], Path)          File "C:\Anaconda3\lib\site-packages\fastai\data_block.py", line 204, in <listcomp>
    return [i for i in range_of(self) if (self.items[i].parts[self.num_parts] if isinstance(self.items[i], Path)        IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by redknightlois** [comment]
No, Fire doesn't work either.

**Comment by redknightlois** [comment]
The error happens here: https://github.com/fastai/fastai/blob/master/fastai/basic_train.py#L99
Apparently when it tries to spawn multiple workers. 
EDIT: Confirmed `num_workers = 0` works... slow as hell but works.

**Comment by mgrankin** [comment]
Great workaround! It's worth submitting a bug to the fastai repo.

**Comment by a793719595** [comment]
> The error happens here: https://github.com/fastai/fastai/blob/master/fastai/basic_train.py#L99
> Apparently when it tries to spawn multiple workers.
> EDIT: Confirmed `num_workers = 0` works... slow as hell but works.
I have the same problem. Where do you set num_workers = 0

**Comment by a793719595** [comment]
I have the same problem. Where do you set num_workers = 0

**Comment by mgrankin** [comment]
You can pass `num_workers` into your `Databunch` constructor, it will pass the param to the `Dataloader`.

**Comment by a793719595** [comment]
Thank you , i find it.
